version: '3.7'

services:
  statamic:
    image: ghcr.io/o1y/statamic-starter:1.0.1-php7.4
    ports:
      - 8080:8080
    volumes:
      - ./statamic/:/var/www/
  mail:
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025
