title: Gallengangkrebs
additional_terms:
  -
    term: 'Cholangiozelluläres Karzinom'
  -
    term: Cholangiokarzinom
updated_by: 31bb3955-fa9f-477e-94b8-d1afcdc3367e
updated_at: 1644324102
blueprint: cancer_type
