title: Blasenkrebs
additional_terms:
  -
    term: Harnblasenkrebs
  -
    term: Blasenkarzinom
  -
    term: Harnblasenkarzinom
updated_by: 31bb3955-fa9f-477e-94b8-d1afcdc3367e
updated_at: 1644344198
blueprint: cancer_type
is_cancer_sub_type: false
