title: Knochenmarkkrebs
is_cancer_sub_type: true
updated_by: 31bb3955-fa9f-477e-94b8-d1afcdc3367e
updated_at: 1647721527
blueprint: cancer_type
additional_terms:
  -
    term: Knochenmarkkarzinom
  -
    term: '(Multiples) Myelom'
cancer_parent_type:
  - lymph-gland-cancer
  - blood-cancer
