title: Leberzellkrebs
additional_terms:
  -
    term: Leberzellkarzinom
  -
    term: 'Hepatozelluläres Karzinom'
is_cancer_sub_type: true
cancer_parent_type:
  - liver-cancer
updated_by: 31bb3955-fa9f-477e-94b8-d1afcdc3367e
updated_at: 1644344729
blueprint: cancer_type
