title: Enddarmkrebs
additional_terms:
  -
    term: Mastdarmkrebs
  -
    term: Rektumkarzinom
is_cancer_sub_type: false
updated_by: 31bb3955-fa9f-477e-94b8-d1afcdc3367e
updated_at: 1651509120
blueprint: cancer_type
