title: Synovialsarkom
additional_terms:
  -
    term: 'Synovialom'
is_cancer_sub_type: true
cancer_parent_type:
  - soft-tissue-cancer
updated_by: 31bb3955-fa9f-477e-94b8-d1afcdc3367e
updated_at: 1647721539
blueprint: cancer_type
