title: Zungengrundkarzinom
additional_terms:
  -
    term: Zungenkrebs
is_cancer_sub_type: true
cancer_parent_type:
  - revenge-tumor
updated_by: 3b7f2d63-0aed-4ba3-824c-3b1650cef8a6
updated_at: 1657893780
blueprint: cancer_type
